[workspace]
members = [".", "crates/steward-proto"]
default-members = ["."]
resolver = "2"

[workspace.package]
version = "4.2.7"
edition = "2021"

[workspace.dependencies]
prost = "0.7"
serde = { version = "1.0", features = ["serde_derive"] }
tonic = { version = "0.4.3", features = [
    "codegen",
    "tls",
    "tower",
    "transport",
] }

[package]
name = "steward"
authors = ["Collin Brittain", "Eric Bolten", "Ukpai Ugochi", "Zaki Manian"]
version.workspace = true
edition.workspace = true
rust-version = "1.76.0"

[dependencies]
abscissa_tokio = { version = "0.8.0", features = ["actix"] }
bip32 = "0.2"
bytes = "1.0"
clap = "4"
clarity = "0.4.12"
deep_space = { git = "https://github.com/iqlusioninc/deep_space/", branch = "master" }
ethers = { git = "https://github.com/iqlusioninc/ethers-rs.git", branch = "zaki/error_abi_support", features = [
    "abigen",
] }
futures = "0.3"
gravity_bridge = { git = "https://github.com/PeggyJV/gravity-bridge", branch = "main" }
hex = "0.4"
hyper = "0.14.12"
iqhttp = { version = "0.1", features = ["json"] }
k256 = { version = "0.9", features = ["pem"] }
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
pkcs8 = { version = "0.7", features = ["pem"] }
prost.workspace = true
prost-types = "0.7"
rand_core = { version = "0.6", features = ["std"] }
rand = "0.8.0"
regex = "1.5.4"
rpassword = "5"
serde.workspace = true
serde_json = "1.0.64"
sha2 = "0.9"
sha3 = "0.10.6"
signatory = "0.23.0-pre"
somm_proto = { git = "https://github.com/PeggyJV/sommelier", rev = "cec0a521bff793c6f01ce05429214113b22a588c" }
steward-proto = { path = "crates/steward-proto" }
thiserror = "1"
tokio = { version = "1", features = ["macros", "fs"] }
toml = { version = "0.5" }
tonic.workspace = true
tonic-reflection = "0.1.0"
tower = { version = "0.4", features = ["buffer", "util"] }
url = "2.2.2"
lazy_static = "1.4.0"

# this is a dirty trick, we depent transitively on OpenSSL it's never
# called directly in this crate, but if we specify this dep we can enable
# this feature for all the crates in our dependency tree which depend on
# this crate. This allows for easy cross compiled builds because the 'vendored'
# feature includes it's own OpenSSL version that's compiled on the fly
# If ANY crate in this workspace has this it will work for all of them.
openssl = { version = "=0.10.71", features = ["vendored"] }
once_cell = "1.10.0"
reqwest = "0.11.14"
rustls = "0.19"
x509-parser = { version = "0.14.0", features = ["verify"] }
rustls-pemfile = "1.0.2"
tokio-util = "0.7.7"
addr = "0.15.6"
openssl-sys = "0.9.106"
openssl-probe = "0.1.6"


[dependencies.abscissa_core]
version = "0.8.1"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.8.1", features = ["testing"] }
assay = "0.1"
hex = "0.4.3"
once_cell = "1.2"
tempdir = "0.3"

[build-dependencies]
ethers = { git = "https://github.com/iqlusioninc/ethers-rs.git", branch = "zaki/error_abi_support", features = [
    "abigen",
] }
hex = "0.4"
merkle_hash = "3.6"
prost-build = "0.7"
tonic = { version = "0.4.3", features = ["codegen", "tls", "transport"] }
tonic-build = "0.4"
walkdir = "2.3.2"
