//
// Protos for governance-executed scheduled corks.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: governance.proto

package steward_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// Represents a governance-executed cellar function call. Used for Scheduled Cork Proposals in Sommelier.
type GovernanceCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of Cellar to call
	//
	// Types that are assignable to Call:
	//	*GovernanceCall_AaveV2Stablecoin
	//	*GovernanceCall_CellarV1
	//	*GovernanceCall_CellarV2
	Call isGovernanceCall_Call `protobuf_oneof:"call"`
}

func (x *GovernanceCall) Reset() {
	*x = GovernanceCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_governance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GovernanceCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceCall) ProtoMessage() {}

func (x *GovernanceCall) ProtoReflect() protoreflect.Message {
	mi := &file_governance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceCall.ProtoReflect.Descriptor instead.
func (*GovernanceCall) Descriptor() ([]byte, []int) {
	return file_governance_proto_rawDescGZIP(), []int{0}
}

func (m *GovernanceCall) GetCall() isGovernanceCall_Call {
	if m != nil {
		return m.Call
	}
	return nil
}

func (x *GovernanceCall) GetAaveV2Stablecoin() *AaveV2StablecoinGovernance {
	if x, ok := x.GetCall().(*GovernanceCall_AaveV2Stablecoin); ok {
		return x.AaveV2Stablecoin
	}
	return nil
}

func (x *GovernanceCall) GetCellarV1() *CellarV1Governance {
	if x, ok := x.GetCall().(*GovernanceCall_CellarV1); ok {
		return x.CellarV1
	}
	return nil
}

func (x *GovernanceCall) GetCellarV2() *CellarV2Governance {
	if x, ok := x.GetCall().(*GovernanceCall_CellarV2); ok {
		return x.CellarV2
	}
	return nil
}

type isGovernanceCall_Call interface {
	isGovernanceCall_Call()
}

type GovernanceCall_AaveV2Stablecoin struct {
	// Governance function calls to the AaveV2Stablecoin cellar
	AaveV2Stablecoin *AaveV2StablecoinGovernance `protobuf:"bytes,2,opt,name=aave_v2_stablecoin,json=aaveV2Stablecoin,proto3,oneof"`
}

type GovernanceCall_CellarV1 struct {
	// Governance function calls to V1 cellars
	CellarV1 *CellarV1Governance `protobuf:"bytes,3,opt,name=cellar_v1,json=cellarV1,proto3,oneof"`
}

type GovernanceCall_CellarV2 struct {
	// Governance function calls to V2 cellars
	CellarV2 *CellarV2Governance `protobuf:"bytes,4,opt,name=cellar_v2,json=cellarV2,proto3,oneof"`
}

func (*GovernanceCall_AaveV2Stablecoin) isGovernanceCall_Call() {}

func (*GovernanceCall_CellarV1) isGovernanceCall_Call() {}

func (*GovernanceCall_CellarV2) isGovernanceCall_Call() {}

var File_governance_proto protoreflect.FileDescriptor

var file_governance_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x33, 0x1a, 0x18,
	0x61, 0x61, 0x76, 0x65, 0x5f, 0x76, 0x32, 0x5f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x72,
	0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x63, 0x65, 0x6c, 0x6c, 0x61,
	0x72, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01, 0x0a, 0x0e, 0x47,
	0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x56, 0x0a,
	0x12, 0x61, 0x61, 0x76, 0x65, 0x5f, 0x76, 0x32, 0x5f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x63,
	0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x2e, 0x76, 0x33, 0x2e, 0x41, 0x61, 0x76, 0x65, 0x56, 0x32, 0x53, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x63, 0x6f, 0x69, 0x6e, 0x47, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x48, 0x00, 0x52, 0x10, 0x61, 0x61, 0x76, 0x65, 0x56, 0x32, 0x53, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x3d, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x5f,
	0x76, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x56, 0x31, 0x47, 0x6f,
	0x76, 0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x65, 0x6c, 0x6c,
	0x61, 0x72, 0x56, 0x31, 0x12, 0x3d, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x5f, 0x76,
	0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x56, 0x32, 0x47, 0x6f, 0x76,
	0x65, 0x72, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x65, 0x6c, 0x6c, 0x61,
	0x72, 0x56, 0x32, 0x42, 0x06, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x42, 0x10, 0x5a, 0x0e, 0x2f,
	0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_governance_proto_rawDescOnce sync.Once
	file_governance_proto_rawDescData = file_governance_proto_rawDesc
)

func file_governance_proto_rawDescGZIP() []byte {
	file_governance_proto_rawDescOnce.Do(func() {
		file_governance_proto_rawDescData = protoimpl.X.CompressGZIP(file_governance_proto_rawDescData)
	})
	return file_governance_proto_rawDescData
}

var file_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_governance_proto_goTypes = []interface{}{
	(*GovernanceCall)(nil),             // 0: steward.v3.GovernanceCall
	(*AaveV2StablecoinGovernance)(nil), // 1: steward.v3.AaveV2StablecoinGovernance
	(*CellarV1Governance)(nil),         // 2: steward.v3.CellarV1Governance
	(*CellarV2Governance)(nil),         // 3: steward.v3.CellarV2Governance
}
var file_governance_proto_depIdxs = []int32{
	1, // 0: steward.v3.GovernanceCall.aave_v2_stablecoin:type_name -> steward.v3.AaveV2StablecoinGovernance
	2, // 1: steward.v3.GovernanceCall.cellar_v1:type_name -> steward.v3.CellarV1Governance
	3, // 2: steward.v3.GovernanceCall.cellar_v2:type_name -> steward.v3.CellarV2Governance
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_governance_proto_init() }
func file_governance_proto_init() {
	if File_governance_proto != nil {
		return
	}
	file_aave_v2_stablecoin_proto_init()
	file_cellar_v1_proto_init()
	file_cellar_v2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_governance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GovernanceCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_governance_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GovernanceCall_AaveV2Stablecoin)(nil),
		(*GovernanceCall_CellarV1)(nil),
		(*GovernanceCall_CellarV2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_governance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_governance_proto_goTypes,
		DependencyIndexes: file_governance_proto_depIdxs,
		MessageInfos:      file_governance_proto_msgTypes,
	}.Build()
	File_governance_proto = out.File
	file_governance_proto_rawDesc = nil
	file_governance_proto_goTypes = nil
	file_governance_proto_depIdxs = nil
}
