//
// Protos for function calls to Boring Vault Manager contracts

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: boring_vault/v1/manager.proto

package steward_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoringVaultManagerWithMerkleVerification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Function:
	//
	//	*BoringVaultManagerWithMerkleVerification_SetManageRoot_
	//	*BoringVaultManagerWithMerkleVerification_Pause_
	//	*BoringVaultManagerWithMerkleVerification_Unpause_
	Function isBoringVaultManagerWithMerkleVerification_Function `protobuf_oneof:"function"`
}

func (x *BoringVaultManagerWithMerkleVerification) Reset() {
	*x = BoringVaultManagerWithMerkleVerification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boring_vault_v1_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoringVaultManagerWithMerkleVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoringVaultManagerWithMerkleVerification) ProtoMessage() {}

func (x *BoringVaultManagerWithMerkleVerification) ProtoReflect() protoreflect.Message {
	mi := &file_boring_vault_v1_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoringVaultManagerWithMerkleVerification.ProtoReflect.Descriptor instead.
func (*BoringVaultManagerWithMerkleVerification) Descriptor() ([]byte, []int) {
	return file_boring_vault_v1_manager_proto_rawDescGZIP(), []int{0}
}

func (m *BoringVaultManagerWithMerkleVerification) GetFunction() isBoringVaultManagerWithMerkleVerification_Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (x *BoringVaultManagerWithMerkleVerification) GetSetManageRoot() *BoringVaultManagerWithMerkleVerification_SetManageRoot {
	if x, ok := x.GetFunction().(*BoringVaultManagerWithMerkleVerification_SetManageRoot_); ok {
		return x.SetManageRoot
	}
	return nil
}

func (x *BoringVaultManagerWithMerkleVerification) GetPause() *BoringVaultManagerWithMerkleVerification_Pause {
	if x, ok := x.GetFunction().(*BoringVaultManagerWithMerkleVerification_Pause_); ok {
		return x.Pause
	}
	return nil
}

func (x *BoringVaultManagerWithMerkleVerification) GetUnpause() *BoringVaultManagerWithMerkleVerification_Unpause {
	if x, ok := x.GetFunction().(*BoringVaultManagerWithMerkleVerification_Unpause_); ok {
		return x.Unpause
	}
	return nil
}

type isBoringVaultManagerWithMerkleVerification_Function interface {
	isBoringVaultManagerWithMerkleVerification_Function()
}

type BoringVaultManagerWithMerkleVerification_SetManageRoot_ struct {
	// Represents function `setManageRoot(address strategist, bytes32 merkleRoot)`
	SetManageRoot *BoringVaultManagerWithMerkleVerification_SetManageRoot `protobuf:"bytes,1,opt,name=set_manage_root,json=setManageRoot,proto3,oneof"`
}

type BoringVaultManagerWithMerkleVerification_Pause_ struct {
	// Represents function `pause()`
	Pause *BoringVaultManagerWithMerkleVerification_Pause `protobuf:"bytes,2,opt,name=pause,proto3,oneof"`
}

type BoringVaultManagerWithMerkleVerification_Unpause_ struct {
	// Represents function `unpause()`
	Unpause *BoringVaultManagerWithMerkleVerification_Unpause `protobuf:"bytes,3,opt,name=unpause,proto3,oneof"`
}

func (*BoringVaultManagerWithMerkleVerification_SetManageRoot_) isBoringVaultManagerWithMerkleVerification_Function() {
}

func (*BoringVaultManagerWithMerkleVerification_Pause_) isBoringVaultManagerWithMerkleVerification_Function() {
}

func (*BoringVaultManagerWithMerkleVerification_Unpause_) isBoringVaultManagerWithMerkleVerification_Function() {
}

// Represents function `setManageRoot(address strategist, bytes32 merkleRoot)`
type BoringVaultManagerWithMerkleVerification_SetManageRoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address of the strategist
	Strategist string `protobuf:"bytes,1,opt,name=strategist,proto3" json:"strategist,omitempty"`
	// The manage root to set
	ManageRoot string `protobuf:"bytes,2,opt,name=manage_root,json=manageRoot,proto3" json:"manage_root,omitempty"`
}

func (x *BoringVaultManagerWithMerkleVerification_SetManageRoot) Reset() {
	*x = BoringVaultManagerWithMerkleVerification_SetManageRoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boring_vault_v1_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoringVaultManagerWithMerkleVerification_SetManageRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoringVaultManagerWithMerkleVerification_SetManageRoot) ProtoMessage() {}

func (x *BoringVaultManagerWithMerkleVerification_SetManageRoot) ProtoReflect() protoreflect.Message {
	mi := &file_boring_vault_v1_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoringVaultManagerWithMerkleVerification_SetManageRoot.ProtoReflect.Descriptor instead.
func (*BoringVaultManagerWithMerkleVerification_SetManageRoot) Descriptor() ([]byte, []int) {
	return file_boring_vault_v1_manager_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BoringVaultManagerWithMerkleVerification_SetManageRoot) GetStrategist() string {
	if x != nil {
		return x.Strategist
	}
	return ""
}

func (x *BoringVaultManagerWithMerkleVerification_SetManageRoot) GetManageRoot() string {
	if x != nil {
		return x.ManageRoot
	}
	return ""
}

// Represents function `pause()`
type BoringVaultManagerWithMerkleVerification_Pause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BoringVaultManagerWithMerkleVerification_Pause) Reset() {
	*x = BoringVaultManagerWithMerkleVerification_Pause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boring_vault_v1_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoringVaultManagerWithMerkleVerification_Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoringVaultManagerWithMerkleVerification_Pause) ProtoMessage() {}

func (x *BoringVaultManagerWithMerkleVerification_Pause) ProtoReflect() protoreflect.Message {
	mi := &file_boring_vault_v1_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoringVaultManagerWithMerkleVerification_Pause.ProtoReflect.Descriptor instead.
func (*BoringVaultManagerWithMerkleVerification_Pause) Descriptor() ([]byte, []int) {
	return file_boring_vault_v1_manager_proto_rawDescGZIP(), []int{0, 1}
}

// Represents function `unpause()`
type BoringVaultManagerWithMerkleVerification_Unpause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BoringVaultManagerWithMerkleVerification_Unpause) Reset() {
	*x = BoringVaultManagerWithMerkleVerification_Unpause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boring_vault_v1_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoringVaultManagerWithMerkleVerification_Unpause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoringVaultManagerWithMerkleVerification_Unpause) ProtoMessage() {}

func (x *BoringVaultManagerWithMerkleVerification_Unpause) ProtoReflect() protoreflect.Message {
	mi := &file_boring_vault_v1_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoringVaultManagerWithMerkleVerification_Unpause.ProtoReflect.Descriptor instead.
func (*BoringVaultManagerWithMerkleVerification_Unpause) Descriptor() ([]byte, []int) {
	return file_boring_vault_v1_manager_proto_rawDescGZIP(), []int{0, 2}
}

var File_boring_vault_v1_manager_proto protoreflect.FileDescriptor

var file_boring_vault_v1_manager_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x22, 0xb8, 0x03, 0x0a, 0x28,
	0x42, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x0f, 0x73, 0x65, 0x74, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x42, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x42,
	0x6f, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x52, 0x0a, 0x05, 0x70, 0x61, 0x75, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e,
	0x76, 0x34, 0x2e, 0x42, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x75, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x70, 0x61, 0x75, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x07, 0x75, 0x6e,
	0x70, 0x61, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x73, 0x74,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x42, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4d,
	0x65, 0x72, 0x6b, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x75, 0x6e, 0x70,
	0x61, 0x75, 0x73, 0x65, 0x1a, 0x50, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x5f,
	0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x1a,
	0x09, 0x0a, 0x07, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x73, 0x74, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_boring_vault_v1_manager_proto_rawDescOnce sync.Once
	file_boring_vault_v1_manager_proto_rawDescData = file_boring_vault_v1_manager_proto_rawDesc
)

func file_boring_vault_v1_manager_proto_rawDescGZIP() []byte {
	file_boring_vault_v1_manager_proto_rawDescOnce.Do(func() {
		file_boring_vault_v1_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_boring_vault_v1_manager_proto_rawDescData)
	})
	return file_boring_vault_v1_manager_proto_rawDescData
}

var file_boring_vault_v1_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_boring_vault_v1_manager_proto_goTypes = []interface{}{
	(*BoringVaultManagerWithMerkleVerification)(nil),               // 0: steward.v4.BoringVaultManagerWithMerkleVerification
	(*BoringVaultManagerWithMerkleVerification_SetManageRoot)(nil), // 1: steward.v4.BoringVaultManagerWithMerkleVerification.SetManageRoot
	(*BoringVaultManagerWithMerkleVerification_Pause)(nil),         // 2: steward.v4.BoringVaultManagerWithMerkleVerification.Pause
	(*BoringVaultManagerWithMerkleVerification_Unpause)(nil),       // 3: steward.v4.BoringVaultManagerWithMerkleVerification.Unpause
}
var file_boring_vault_v1_manager_proto_depIdxs = []int32{
	1, // 0: steward.v4.BoringVaultManagerWithMerkleVerification.set_manage_root:type_name -> steward.v4.BoringVaultManagerWithMerkleVerification.SetManageRoot
	2, // 1: steward.v4.BoringVaultManagerWithMerkleVerification.pause:type_name -> steward.v4.BoringVaultManagerWithMerkleVerification.Pause
	3, // 2: steward.v4.BoringVaultManagerWithMerkleVerification.unpause:type_name -> steward.v4.BoringVaultManagerWithMerkleVerification.Unpause
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_boring_vault_v1_manager_proto_init() }
func file_boring_vault_v1_manager_proto_init() {
	if File_boring_vault_v1_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_boring_vault_v1_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoringVaultManagerWithMerkleVerification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boring_vault_v1_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoringVaultManagerWithMerkleVerification_SetManageRoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boring_vault_v1_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoringVaultManagerWithMerkleVerification_Pause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boring_vault_v1_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoringVaultManagerWithMerkleVerification_Unpause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_boring_vault_v1_manager_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BoringVaultManagerWithMerkleVerification_SetManageRoot_)(nil),
		(*BoringVaultManagerWithMerkleVerification_Pause_)(nil),
		(*BoringVaultManagerWithMerkleVerification_Unpause_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_boring_vault_v1_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boring_vault_v1_manager_proto_goTypes,
		DependencyIndexes: file_boring_vault_v1_manager_proto_depIdxs,
		MessageInfos:      file_boring_vault_v1_manager_proto_msgTypes,
	}.Build()
	File_boring_vault_v1_manager_proto = out.File
	file_boring_vault_v1_manager_proto_rawDesc = nil
	file_boring_vault_v1_manager_proto_goTypes = nil
	file_boring_vault_v1_manager_proto_depIdxs = nil
}
