// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.1
// source: uniswap_v3.proto

package steward_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents call data for the Uniswap V3 adaptor
type UniswapV3AdaptorV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Function:
	//
	//	*UniswapV3AdaptorV2_RevokeApproval
	//	*UniswapV3AdaptorV2_OpenPosition_
	//	*UniswapV3AdaptorV2_ClosePosition_
	//	*UniswapV3AdaptorV2_AddToPosition_
	//	*UniswapV3AdaptorV2_TakeFromPosition_
	//	*UniswapV3AdaptorV2_CollectFees_
	//	*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions_
	//	*UniswapV3AdaptorV2_PurgeSinglePosition_
	//	*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker_
	Function isUniswapV3AdaptorV2_Function `protobuf_oneof:"function"`
}

func (x *UniswapV3AdaptorV2) Reset() {
	*x = UniswapV3AdaptorV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2) ProtoMessage() {}

func (x *UniswapV3AdaptorV2) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0}
}

func (m *UniswapV3AdaptorV2) GetFunction() isUniswapV3AdaptorV2_Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetRevokeApproval() *RevokeApproval {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_RevokeApproval); ok {
		return x.RevokeApproval
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetOpenPosition() *UniswapV3AdaptorV2_OpenPosition {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_OpenPosition_); ok {
		return x.OpenPosition
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetClosePosition() *UniswapV3AdaptorV2_ClosePosition {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_ClosePosition_); ok {
		return x.ClosePosition
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetAddToPosition() *UniswapV3AdaptorV2_AddToPosition {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_AddToPosition_); ok {
		return x.AddToPosition
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetTakeFromPosition() *UniswapV3AdaptorV2_TakeFromPosition {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_TakeFromPosition_); ok {
		return x.TakeFromPosition
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetCollectFees() *UniswapV3AdaptorV2_CollectFees {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_CollectFees_); ok {
		return x.CollectFees
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetPurgeAllZeroLiquidityPositions() *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions_); ok {
		return x.PurgeAllZeroLiquidityPositions
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetPurgeSinglePosition() *UniswapV3AdaptorV2_PurgeSinglePosition {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_PurgeSinglePosition_); ok {
		return x.PurgeSinglePosition
	}
	return nil
}

func (x *UniswapV3AdaptorV2) GetRemoveUnownedPositionFromTracker() *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker {
	if x, ok := x.GetFunction().(*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker_); ok {
		return x.RemoveUnownedPositionFromTracker
	}
	return nil
}

type isUniswapV3AdaptorV2_Function interface {
	isUniswapV3AdaptorV2_Function()
}

type UniswapV3AdaptorV2_RevokeApproval struct {
	// Represents function `revokeApproval(ERC20 asset, address spender)`
	RevokeApproval *RevokeApproval `protobuf:"bytes,1,opt,name=revoke_approval,json=revokeApproval,proto3,oneof"`
}

type UniswapV3AdaptorV2_OpenPosition_ struct {
	// Represents function `openPosition(ERC20 token0, ERC20 token1, uint24 poolFee, uint256 amount0, uint256 amount1, uint256 min0, uint256 min1, int24 tickLower, int24 tickUpper)`
	OpenPosition *UniswapV3AdaptorV2_OpenPosition `protobuf:"bytes,2,opt,name=open_position,json=openPosition,proto3,oneof"`
}

type UniswapV3AdaptorV2_ClosePosition_ struct {
	// Represents function `closePosition(uint256 positionId, uint256 min0, uint256 min1)`
	ClosePosition *UniswapV3AdaptorV2_ClosePosition `protobuf:"bytes,3,opt,name=close_position,json=closePosition,proto3,oneof"`
}

type UniswapV3AdaptorV2_AddToPosition_ struct {
	// Represents function `addToPosition(uint256 positionId, uint256 amount0, uint256 amount1, uint256 min0, uint256 min1)`
	AddToPosition *UniswapV3AdaptorV2_AddToPosition `protobuf:"bytes,4,opt,name=add_to_position,json=addToPosition,proto3,oneof"`
}

type UniswapV3AdaptorV2_TakeFromPosition_ struct {
	// Represents function `takeFromPosition(uint256 positionId, uint128 liquidity, uint256 min0, uint256 min1, bool collectFees)`
	TakeFromPosition *UniswapV3AdaptorV2_TakeFromPosition `protobuf:"bytes,5,opt,name=take_from_position,json=takeFromPosition,proto3,oneof"`
}

type UniswapV3AdaptorV2_CollectFees_ struct {
	// Represents function `collectFees(uint256 positionId, uint128 amount0, uint128 amount1)`
	CollectFees *UniswapV3AdaptorV2_CollectFees `protobuf:"bytes,6,opt,name=collect_fees,json=collectFees,proto3,oneof"`
}

type UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions_ struct {
	// Represents function `purgeAllZeroLiquidityPositions(ERC20 token0, ERC20 token1)`
	PurgeAllZeroLiquidityPositions *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions `protobuf:"bytes,7,opt,name=purge_all_zero_liquidity_positions,json=purgeAllZeroLiquidityPositions,proto3,oneof"`
}

type UniswapV3AdaptorV2_PurgeSinglePosition_ struct {
	// Represents function `purgeSinglePosition(uint256 tokenId)`
	PurgeSinglePosition *UniswapV3AdaptorV2_PurgeSinglePosition `protobuf:"bytes,8,opt,name=purge_single_position,json=purgeSinglePosition,proto3,oneof"`
}

type UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker_ struct {
	// Represents function `removeUnOwnedPositionFromTracker(uint256 tokenId, ERC20 token0, ERC20 token1)`
	RemoveUnownedPositionFromTracker *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker `protobuf:"bytes,9,opt,name=remove_unowned_position_from_tracker,json=removeUnownedPositionFromTracker,proto3,oneof"`
}

func (*UniswapV3AdaptorV2_RevokeApproval) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_OpenPosition_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_ClosePosition_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_AddToPosition_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_TakeFromPosition_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_CollectFees_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_PurgeSinglePosition_) isUniswapV3AdaptorV2_Function() {}

func (*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker_) isUniswapV3AdaptorV2_Function() {}

type UniswapV3AdaptorV2Calls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls []*UniswapV3AdaptorV2 `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
}

func (x *UniswapV3AdaptorV2Calls) Reset() {
	*x = UniswapV3AdaptorV2Calls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2Calls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2Calls) ProtoMessage() {}

func (x *UniswapV3AdaptorV2Calls) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2Calls.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2Calls) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{1}
}

func (x *UniswapV3AdaptorV2Calls) GetCalls() []*UniswapV3AdaptorV2 {
	if x != nil {
		return x.Calls
	}
	return nil
}

// Allows strategist to open up arbritray Uniswap V3 positions.
//
// Represents function openPosition(ERC20 token0, ERC20 token1, uint24 poolFee, uint256 amount0, uint256 amount1, uint256 min0, uint256 min1, int24 tickLower, int24 tickUpper)
type UniswapV3AdaptorV2_OpenPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token_0   string `protobuf:"bytes,1,opt,name=token_0,json=token0,proto3" json:"token_0,omitempty"`
	Token_1   string `protobuf:"bytes,2,opt,name=token_1,json=token1,proto3" json:"token_1,omitempty"`
	PoolFee   uint32 `protobuf:"varint,3,opt,name=pool_fee,json=poolFee,proto3" json:"pool_fee,omitempty"`
	Amount_0  string `protobuf:"bytes,4,opt,name=amount_0,json=amount0,proto3" json:"amount_0,omitempty"`
	Amount_1  string `protobuf:"bytes,5,opt,name=amount_1,json=amount1,proto3" json:"amount_1,omitempty"`
	Min_0     string `protobuf:"bytes,6,opt,name=min_0,json=min0,proto3" json:"min_0,omitempty"`
	Min_1     string `protobuf:"bytes,7,opt,name=min_1,json=min1,proto3" json:"min_1,omitempty"`
	TickLower int32  `protobuf:"varint,8,opt,name=tick_lower,json=tickLower,proto3" json:"tick_lower,omitempty"`
	TickUpper int32  `protobuf:"varint,9,opt,name=tick_upper,json=tickUpper,proto3" json:"tick_upper,omitempty"`
}

func (x *UniswapV3AdaptorV2_OpenPosition) Reset() {
	*x = UniswapV3AdaptorV2_OpenPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_OpenPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_OpenPosition) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_OpenPosition) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_OpenPosition.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_OpenPosition) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetToken_0() string {
	if x != nil {
		return x.Token_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetToken_1() string {
	if x != nil {
		return x.Token_1
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetPoolFee() uint32 {
	if x != nil {
		return x.PoolFee
	}
	return 0
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetAmount_0() string {
	if x != nil {
		return x.Amount_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetAmount_1() string {
	if x != nil {
		return x.Amount_1
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetMin_0() string {
	if x != nil {
		return x.Min_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetMin_1() string {
	if x != nil {
		return x.Min_1
	}
	return ""
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetTickLower() int32 {
	if x != nil {
		return x.TickLower
	}
	return 0
}

func (x *UniswapV3AdaptorV2_OpenPosition) GetTickUpper() int32 {
	if x != nil {
		return x.TickUpper
	}
	return 0
}

// Allows strategist to close Uniswap V3 positions.
//
// Represents function `closePosition(uint256 tokenId, uint256 min0, uint256 min1)`
type UniswapV3AdaptorV2_ClosePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Min_0   string `protobuf:"bytes,2,opt,name=min_0,json=min0,proto3" json:"min_0,omitempty"`
	Min_1   string `protobuf:"bytes,3,opt,name=min_1,json=min1,proto3" json:"min_1,omitempty"`
}

func (x *UniswapV3AdaptorV2_ClosePosition) Reset() {
	*x = UniswapV3AdaptorV2_ClosePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_ClosePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_ClosePosition) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_ClosePosition) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_ClosePosition.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_ClosePosition) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UniswapV3AdaptorV2_ClosePosition) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UniswapV3AdaptorV2_ClosePosition) GetMin_0() string {
	if x != nil {
		return x.Min_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_ClosePosition) GetMin_1() string {
	if x != nil {
		return x.Min_1
	}
	return ""
}

// Allows strategist to add to existing Uniswap V3 positions.
//
// Represents function `addToPosition(uint256 tokenId, uint256 amount0, uint256 amount1, uint256 min0, uint256 min1)`
type UniswapV3AdaptorV2_AddToPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Amount_0 string `protobuf:"bytes,2,opt,name=amount_0,json=amount0,proto3" json:"amount_0,omitempty"`
	Amount_1 string `protobuf:"bytes,3,opt,name=amount_1,json=amount1,proto3" json:"amount_1,omitempty"`
	Min_0    string `protobuf:"bytes,4,opt,name=min_0,json=min0,proto3" json:"min_0,omitempty"`
	Min_1    string `protobuf:"bytes,5,opt,name=min_1,json=min1,proto3" json:"min_1,omitempty"`
}

func (x *UniswapV3AdaptorV2_AddToPosition) Reset() {
	*x = UniswapV3AdaptorV2_AddToPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_AddToPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_AddToPosition) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_AddToPosition) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_AddToPosition.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_AddToPosition) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 2}
}

func (x *UniswapV3AdaptorV2_AddToPosition) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UniswapV3AdaptorV2_AddToPosition) GetAmount_0() string {
	if x != nil {
		return x.Amount_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_AddToPosition) GetAmount_1() string {
	if x != nil {
		return x.Amount_1
	}
	return ""
}

func (x *UniswapV3AdaptorV2_AddToPosition) GetMin_0() string {
	if x != nil {
		return x.Min_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_AddToPosition) GetMin_1() string {
	if x != nil {
		return x.Min_1
	}
	return ""
}

// Allows strategist to take from existing Uniswap V3 positions.
//
// Represents function `takeFromPosition(uint256 tokenId, uint128 liquidity, uint256 min0, uint256 min1, bool takeFees)`
type UniswapV3AdaptorV2_TakeFromPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId   string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Liquidity string `protobuf:"bytes,2,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	Min_0     string `protobuf:"bytes,3,opt,name=min_0,json=min0,proto3" json:"min_0,omitempty"`
	Min_1     string `protobuf:"bytes,4,opt,name=min_1,json=min1,proto3" json:"min_1,omitempty"`
	TakeFees  bool   `protobuf:"varint,5,opt,name=take_fees,json=takeFees,proto3" json:"take_fees,omitempty"`
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) Reset() {
	*x = UniswapV3AdaptorV2_TakeFromPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_TakeFromPosition) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_TakeFromPosition) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_TakeFromPosition.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_TakeFromPosition) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 3}
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) GetLiquidity() string {
	if x != nil {
		return x.Liquidity
	}
	return ""
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) GetMin_0() string {
	if x != nil {
		return x.Min_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) GetMin_1() string {
	if x != nil {
		return x.Min_1
	}
	return ""
}

func (x *UniswapV3AdaptorV2_TakeFromPosition) GetTakeFees() bool {
	if x != nil {
		return x.TakeFees
	}
	return false
}

// Allows strategist to collect fees from existing Uniswap V3 positions.
//
// Represents function `collectFees(uint256 tokenId, uint128 amount0, uint128 amount1)`
type UniswapV3AdaptorV2_CollectFees struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Amount_0 string `protobuf:"bytes,2,opt,name=amount_0,json=amount0,proto3" json:"amount_0,omitempty"`
	Amount_1 string `protobuf:"bytes,3,opt,name=amount_1,json=amount1,proto3" json:"amount_1,omitempty"`
}

func (x *UniswapV3AdaptorV2_CollectFees) Reset() {
	*x = UniswapV3AdaptorV2_CollectFees{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_CollectFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_CollectFees) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_CollectFees) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_CollectFees.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_CollectFees) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 4}
}

func (x *UniswapV3AdaptorV2_CollectFees) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UniswapV3AdaptorV2_CollectFees) GetAmount_0() string {
	if x != nil {
		return x.Amount_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_CollectFees) GetAmount_1() string {
	if x != nil {
		return x.Amount_1
	}
	return ""
}

// Allows strategist to purge zero liquidity LP positions from tracker.
//
// Represents function `purgeAllZeroLiquidityPositions(ERC20 token0, ERC20 token1)`
type UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token_0 string `protobuf:"bytes,1,opt,name=token_0,json=token0,proto3" json:"token_0,omitempty"`
	Token_1 string `protobuf:"bytes,2,opt,name=token_1,json=token1,proto3" json:"token_1,omitempty"`
}

func (x *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) Reset() {
	*x = UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 5}
}

func (x *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) GetToken_0() string {
	if x != nil {
		return x.Token_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions) GetToken_1() string {
	if x != nil {
		return x.Token_1
	}
	return ""
}

// Allows strategist to purge a single zero liquidity LP position from tracker.
//
// Represents function `purgeSinglePosition(uint256 tokenId)`
type UniswapV3AdaptorV2_PurgeSinglePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *UniswapV3AdaptorV2_PurgeSinglePosition) Reset() {
	*x = UniswapV3AdaptorV2_PurgeSinglePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_PurgeSinglePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_PurgeSinglePosition) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_PurgeSinglePosition) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_PurgeSinglePosition.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_PurgeSinglePosition) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 6}
}

func (x *UniswapV3AdaptorV2_PurgeSinglePosition) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// Allows strategist to remove tracked positions that are not owned by the cellar.
//
// Represents function `removeUnOwnedPositionFromTracker(uint256 tokenId, ERC20 token0, ERC20 token1)`
type UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Token_0 string `protobuf:"bytes,2,opt,name=token_0,json=token0,proto3" json:"token_0,omitempty"`
	Token_1 string `protobuf:"bytes,3,opt,name=token_1,json=token1,proto3" json:"token_1,omitempty"`
}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) Reset() {
	*x = UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uniswap_v3_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) ProtoMessage() {}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) ProtoReflect() protoreflect.Message {
	mi := &file_uniswap_v3_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker.ProtoReflect.Descriptor instead.
func (*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) Descriptor() ([]byte, []int) {
	return file_uniswap_v3_proto_rawDescGZIP(), []int{0, 7}
}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) GetToken_0() string {
	if x != nil {
		return x.Token_0
	}
	return ""
}

func (x *UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker) GetToken_1() string {
	if x != nil {
		return x.Token_1
	}
	return ""
}

var File_uniswap_v3_proto protoreflect.FileDescriptor

var file_uniswap_v3_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x76, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x1a, 0x0a,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x0e, 0x0a, 0x12, 0x55,
	0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56,
	0x32, 0x12, 0x45, 0x0a, 0x0f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x52, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69,
	0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c,
	0x6f, 0x70, 0x65, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x55, 0x0a, 0x0e,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74,
	0x6f, 0x72, 0x56, 0x32, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73,
	0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61,
	0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x2e, 0x41, 0x64, 0x64,
	0x54, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x64,
	0x64, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5f, 0x0a, 0x12, 0x74,
	0x61, 0x6b, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64,
	0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x74, 0x61, 0x6b, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x0c,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e,
	0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72,
	0x56, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x65, 0x65, 0x73, 0x48, 0x00,
	0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x65, 0x65, 0x73, 0x12, 0x8b, 0x01,
	0x0a, 0x22, 0x70, 0x75, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x7a, 0x65, 0x72, 0x6f,
	0x5f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x73, 0x74, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56,
	0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65,
	0x41, 0x6c, 0x6c, 0x5a, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x1e, 0x70, 0x75, 0x72,
	0x67, 0x65, 0x41, 0x6c, 0x6c, 0x5a, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x68, 0x0a, 0x15, 0x70,
	0x75, 0x72, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x73, 0x74, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56,
	0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x13, 0x70, 0x75, 0x72, 0x67, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x91, 0x01, 0x0a, 0x24, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x75, 0x6e, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61, 0x70, 0x74,
	0x6f, 0x72, 0x56, 0x32, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x6e, 0x6f, 0x77, 0x6e,
	0x65, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x48, 0x00, 0x52, 0x20, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55,
	0x6e, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72,
	0x6f, 0x6d, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x1a, 0xf9, 0x01, 0x0a, 0x0c, 0x4f, 0x70,
	0x65, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x30, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x31, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x6f, 0x6f, 0x6c, 0x46, 0x65, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x30, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x31, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x31, 0x12, 0x13, 0x0a,
	0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x30, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69,
	0x6e, 0x30, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x31, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x5f,
	0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x63,
	0x6b, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x5f, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x63, 0x6b,
	0x55, 0x70, 0x70, 0x65, 0x72, 0x1a, 0x54, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49,
	0x64, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x69, 0x6e, 0x30, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x31, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x31, 0x1a, 0x8a, 0x01, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x30, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x31, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x31, 0x12, 0x13,
	0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x30, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x69, 0x6e, 0x30, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x31, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x31, 0x1a, 0x92, 0x01, 0x0a, 0x10, 0x54, 0x61, 0x6b,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x71, 0x75,
	0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x5f, 0x30, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x30, 0x12, 0x13, 0x0a, 0x05, 0x6d,
	0x69, 0x6e, 0x5f, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x31,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x6b, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x61, 0x6b, 0x65, 0x46, 0x65, 0x65, 0x73, 0x1a, 0x5e, 0x0a,
	0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x65, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x30, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x31, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x31, 0x1a, 0x52, 0x0a,
	0x1e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x41, 0x6c, 0x6c, 0x5a, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x1a, 0x30, 0x0a, 0x13, 0x50, 0x75, 0x72, 0x67, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x64, 0x1a, 0x6f, 0x0a, 0x20, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x6e, 0x6f,
	0x77, 0x6e, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x30, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x31, 0x42, 0x0a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x4f, 0x0a, 0x17, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56, 0x33, 0x41, 0x64, 0x61,
	0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x63,
	0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x34, 0x2e, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x56,
	0x33, 0x41, 0x64, 0x61, 0x70, 0x74, 0x6f, 0x72, 0x56, 0x32, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c,
	0x73, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x73, 0x74, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uniswap_v3_proto_rawDescOnce sync.Once
	file_uniswap_v3_proto_rawDescData = file_uniswap_v3_proto_rawDesc
)

func file_uniswap_v3_proto_rawDescGZIP() []byte {
	file_uniswap_v3_proto_rawDescOnce.Do(func() {
		file_uniswap_v3_proto_rawDescData = protoimpl.X.CompressGZIP(file_uniswap_v3_proto_rawDescData)
	})
	return file_uniswap_v3_proto_rawDescData
}

var file_uniswap_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_uniswap_v3_proto_goTypes = []interface{}{
	(*UniswapV3AdaptorV2)(nil),                                  // 0: steward.v4.UniswapV3AdaptorV2
	(*UniswapV3AdaptorV2Calls)(nil),                             // 1: steward.v4.UniswapV3AdaptorV2Calls
	(*UniswapV3AdaptorV2_OpenPosition)(nil),                     // 2: steward.v4.UniswapV3AdaptorV2.OpenPosition
	(*UniswapV3AdaptorV2_ClosePosition)(nil),                    // 3: steward.v4.UniswapV3AdaptorV2.ClosePosition
	(*UniswapV3AdaptorV2_AddToPosition)(nil),                    // 4: steward.v4.UniswapV3AdaptorV2.AddToPosition
	(*UniswapV3AdaptorV2_TakeFromPosition)(nil),                 // 5: steward.v4.UniswapV3AdaptorV2.TakeFromPosition
	(*UniswapV3AdaptorV2_CollectFees)(nil),                      // 6: steward.v4.UniswapV3AdaptorV2.CollectFees
	(*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions)(nil),   // 7: steward.v4.UniswapV3AdaptorV2.PurgeAllZeroLiquidityPositions
	(*UniswapV3AdaptorV2_PurgeSinglePosition)(nil),              // 8: steward.v4.UniswapV3AdaptorV2.PurgeSinglePosition
	(*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker)(nil), // 9: steward.v4.UniswapV3AdaptorV2.RemoveUnownedPositionFromTracker
	(*RevokeApproval)(nil),                                      // 10: steward.v4.RevokeApproval
}
var file_uniswap_v3_proto_depIdxs = []int32{
	10, // 0: steward.v4.UniswapV3AdaptorV2.revoke_approval:type_name -> steward.v4.RevokeApproval
	2,  // 1: steward.v4.UniswapV3AdaptorV2.open_position:type_name -> steward.v4.UniswapV3AdaptorV2.OpenPosition
	3,  // 2: steward.v4.UniswapV3AdaptorV2.close_position:type_name -> steward.v4.UniswapV3AdaptorV2.ClosePosition
	4,  // 3: steward.v4.UniswapV3AdaptorV2.add_to_position:type_name -> steward.v4.UniswapV3AdaptorV2.AddToPosition
	5,  // 4: steward.v4.UniswapV3AdaptorV2.take_from_position:type_name -> steward.v4.UniswapV3AdaptorV2.TakeFromPosition
	6,  // 5: steward.v4.UniswapV3AdaptorV2.collect_fees:type_name -> steward.v4.UniswapV3AdaptorV2.CollectFees
	7,  // 6: steward.v4.UniswapV3AdaptorV2.purge_all_zero_liquidity_positions:type_name -> steward.v4.UniswapV3AdaptorV2.PurgeAllZeroLiquidityPositions
	8,  // 7: steward.v4.UniswapV3AdaptorV2.purge_single_position:type_name -> steward.v4.UniswapV3AdaptorV2.PurgeSinglePosition
	9,  // 8: steward.v4.UniswapV3AdaptorV2.remove_unowned_position_from_tracker:type_name -> steward.v4.UniswapV3AdaptorV2.RemoveUnownedPositionFromTracker
	0,  // 9: steward.v4.UniswapV3AdaptorV2Calls.calls:type_name -> steward.v4.UniswapV3AdaptorV2
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_uniswap_v3_proto_init() }
func file_uniswap_v3_proto_init() {
	if File_uniswap_v3_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_uniswap_v3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2Calls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_OpenPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_ClosePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_AddToPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_TakeFromPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_CollectFees); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_PurgeSinglePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uniswap_v3_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_uniswap_v3_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UniswapV3AdaptorV2_RevokeApproval)(nil),
		(*UniswapV3AdaptorV2_OpenPosition_)(nil),
		(*UniswapV3AdaptorV2_ClosePosition_)(nil),
		(*UniswapV3AdaptorV2_AddToPosition_)(nil),
		(*UniswapV3AdaptorV2_TakeFromPosition_)(nil),
		(*UniswapV3AdaptorV2_CollectFees_)(nil),
		(*UniswapV3AdaptorV2_PurgeAllZeroLiquidityPositions_)(nil),
		(*UniswapV3AdaptorV2_PurgeSinglePosition_)(nil),
		(*UniswapV3AdaptorV2_RemoveUnownedPositionFromTracker_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uniswap_v3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uniswap_v3_proto_goTypes,
		DependencyIndexes: file_uniswap_v3_proto_depIdxs,
		MessageInfos:      file_uniswap_v3_proto_msgTypes,
	}.Build()
	File_uniswap_v3_proto = out.File
	file_uniswap_v3_proto_rawDesc = nil
	file_uniswap_v3_proto_goTypes = nil
	file_uniswap_v3_proto_depIdxs = nil
}
